name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine base and head refs
        id: refs
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "BASE=${{ github.event.before }}" >> $GITHUB_OUTPUT
            echo "HEAD=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          base: ${{ steps.refs.outputs.BASE }}
          ref: ${{ steps.refs.outputs.HEAD }}
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  frontend-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Format
        run: npm run format

      - name: Run ESLint
        run: npm run lint

      - name: Run test
        run: npm test

  backend-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test
