name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed
        run: |
          echo "BASE_REF=${{ github.base_ref }}" >> $GITHUB_ENV
          echo "HEAD_REF=${{ github.sha }}" >> $GITHUB_ENV

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"

  frontend-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Format
        run: npm run format

      - name: Run ESLint
        run: npm run lint

      - name: Run test
        run: npm test
